:targets:
  - :name:     snowplow-  # Insert your own name to identify the database
    :type:     redshift
    :host:     a0007-cxar-ato-clickstream-jwn.c9gybgr1jgvx.us-west-2.redshift.amazonaws.com  # Insert Redshfit host
    :database:   # Insert database name
    :port:     5439  # Insert database port
    :username:  # Insert username with relevant credentials to run the below queries
    :password:  # Insert user password
:steps:
  - :name: get-last-etls
    :queries:
      - :name: get-last-etls
        :file: ./atomic/copy-events/get-last-etl.sql
  - :name: get-event-ids-from-last-etls
    :queries:
      - :name: get-event-ids-from-last-etls
        :file: ./atomic/copy-events/log-event-ids.sql
  - :name: copy-events
    :queries:
      - :name: copy-events
        :file: ./atomic/copy-events/copy-events.sql
  - :name: copy-nordstrom-child-tables-1
    :queries:
      - :name: nordstrom_add_item
        :file: ./atomic/copy-events/nordstrom_add_item.sql
      - :name: order_items
        :file: ./atomic/copy-events/order_items.sql
      - :name: page_views
        :file: ./atomic/copy-events/page_views.sql
      - :name: product_views
        :file: ./atomic/copy-events/product_views.sql
      - :name: nordstrom_remove_item
        :file: ./atomic/copy-events/nordstrom_remove_item.sql
  - :name: copy-nordstrom-child-tables-2
      - :name: marketing
        :file: ./atomic/copy-events/marketing.sql
      - :name: elwin_exposures
        :file: ./atomic/copy-events/elwin_exposures.sql
    :queries:
  - :name: copy-snowplow-child-tables
    :queries:
      - :name: snowplow_add_to_cart
        :file: ./atomic/copy-events/snowplow_add_to_cart.sql
      - :name: link_clicks
        :file: ./atomic/copy-events/link_clicks.sql
      - :name: snowplow_remove_from_cart
        :file: ./atomic/copy-events/snowplow_remove_from_cart.sql
      - :name: search
        :file: ./atomic/copy-events/search.sql
      - :name: timing
        :file: ./atomic/copy-events/timing.sql
  - :name: update-etl-manifest
    :queries:
      - :name: update-etl-manifest
        :file: ./atomic/copy-events/log-etl-manifest.sql