:targets:
  - :name:     snowplow-  # Insert your own name to identify the database
    :type:     redshift
    :host:     a0007-cxar-ato-clickstream-jwn.c9gybgr1jgvx.us-west-2.redshift.amazonaws.com  # Insert Redshfit host
    :database:   # Insert database name
    :port:     5439  # Insert database port
    :username:  # Insert username with relevant credentials to run the below queries
    :password:  # Insert user password
:steps:
  - :name: get-last-etls
    :queries:
      - :name: get-last-etls
        :file: ./atomic/copy-events/get-last-etl.sql
  - :name: get-event-ids-from-last-etls
    :queries:
      - :name: get-event-ids-from-last-etls
        :file: ./atomic/copy-events/log-event-ids.sql
  - :name: copy-events
    :queries:
      - :name: copy-events
        :file: ./atomic/copy-events/copy-events.sql
  - :name: copy-nordstrom-child-tables-1
    :queries:
      - :name: nordstrom-add-item
        :file: ./atomic/copy-events/nordstrom-add-item.sql
      - :name: order-items
        :file: ./atomic/copy-events/order-items.sql
      - :name: page-views
        :file: ./atomic/copy-events/page-views.sql
      - :name: product-views
        :file: ./atomic/copy-events/product-views.sql
      - :name: nordstrom-remove-item
        :file: ./atomic/copy-events/nordstrom-remove-item.sql
  - :name: copy-nordstrom-child-tables-2
    :queries:
      - :name: marketing
        :file: ./atomic/copy-events/marketing.sql
      - :name: site-promos
        :file: ./atomic/copy-events/site-promos.sql
      - :name: real-estate
        :file: ./atomic/copy-events/real-estate.sql
      - :name: elwin-exposures
        :file: ./atomic/copy-events/elwin-exposures.sql
  - :name: copy-snowplow-child-tables
    :queries:
      - :name: snowplow-add-to-cart
        :file: ./atomic/copy-events/snowplow-add-to-cart.sql
      - :name: link-clicks
        :file: ./atomic/copy-events/link-clicks.sql
      - :name: snowplow-remove-from-cart
        :file: ./atomic/copy-events/snowplow-remove-from-cart.sql
      - :name: search
        :file: ./atomic/copy-events/search.sql
      - :name: timing
        :file: ./atomic/copy-events/timing.sql
