:targets:
  - :name:     snowplow-dev  # Insert your own name to identify the database
    :type:     redshift
    :host:     a0007-cxar-ato-clickstream-jwn.c9gybgr1jgvx.us-west-2.redshift.amazonaws.com  # Insert Redshfit host
    :database: snowplowdev  # Insert database name
    :port:     5439  # Insert database port
    :username:  # Insert username with relevant credentials to run the below queries
    :password:  # Insert user password
:steps:
  - :name: events
    :queries:
      - :name: events
        :file: ./public/deduplicate/events.sql
  - :name: orders
    :queries:
      - :name: orders
        :file: ./public/deduplicate/orders.sql
  - :name: nordstrom-children-1
    :queries:
      - :name: nordstrom-add-item
        :file: ./public/deduplicate/nordstrom-add-item.sql
      - :name: order-items
        :file: ./public/deduplicate/order-items.sql
      - :name: page-views
        :file: ./public/deduplicate/page-views.sql
      - :name: product-views
        :file: ./public/deduplicate/product-views.sql
      - :name: nordstrom-remove-item
        :file: ./public/deduplicate/nordstrom-remove-item.sql
  - :name: nordstrom-children-2
    :queries:
      - :name: marketing
        :file: ./public/deduplicate/marketing.sql
      - :name: site-promos
        :file: ./public/deduplicate/site-promos.sql
      - :name: real-estate
        :file: ./public/deduplicate/real-estate.sql
      - :name: elwin-exposures
        :file: ./public/deduplicate/elwin-exposures.sql
  - :name: 03-snowplow-children
    :queries:
      - :name: snowplow-add-to-cart
        :file: ./public/deduplicate/snowplow-add-to-cart.sql
      - :name: snowplow-link-click
        :file: ./public/deduplicate/link-clicks.sql
      - :name: snowplow-remove-from-cart
        :file: ./public/deduplicate/snowplow-remove-from-cart.sql
      - :name: snowplow-site-search
        :file: ./public/deduplicate/search.sql
      - :name: snowplow-timing
        :file: ./public/deduplicate/timing.sql