:targets:
  - :name:     snowplow-dev  # Insert your own name to identify the database
    :type:     redshift
    :host:     a0007-cxar-ato-clickstream.c9gybgr1jgvx.us-west-2.redshift.amazonaws.com  # Insert Redshfit host
    :database: snowplowprod  # Insert database name
    :port:     5439  # Insert database port
    :username: # Insert username with relevant credentials to run the below queries
    :password: # Insert user password
:steps:
  - :name: 01-events
    :queries:
      - :name: events
        :file: ./public/deduplicate/events.sql
  - :name: 02-orders
    :queries:
      - :name: orders
        :file: ./public/deduplicate/orders.sql
  - :name: 03-nordstrom-children
    :queries:
      - :name: com-nordstrom-add-item-attrs
        :file: ./public/deduplicate/com-nordstrom-add-item-attrs.sql
      - :name: com-nordstrom-elwin-exposures
        :file: ./public/deduplicate/com-nordstrom-elwin-exposures.sql
      - :name: com-nordstrom-order-item-attrs
        :file: ./public/deduplicate/com-nordstrom-order-item-attrs.sql
      - :name: com-nordstrom-page-view-attrs
        :file: ./public/deduplicate/com-nordstrom-page-view-attrs.sql
      - :name: com-nordstrom-product-view-attrs
        :file: ./public/deduplicate/com-nordstrom-product-view-attrs.sql
      - :name: com-nordstrom-remove-item-attrs
        :file: ./public/deduplicate/com-nordstrom-remove-item-attrs.sql
  - :name: 03-snowplow-children
    :queries:
      - :name: com-snowplowanalytics-snowplow-add-to-cart
        :file: ./public/deduplicate/com-snowplowanalytics-snowplow-add-to-cart.sql
      - :name: com-snowplowanalytics-snowplow-link-click
        :file: ./public/deduplicate/com-snowplowanalytics-snowplow-link-click.sql
      - :name: com-snowplowanalytics-snowplow-remove-from-cart
        :file: ./public/deduplicate/com-snowplowanalytics-snowplow-remove-from-cart.sql
      - :name: com-snowplowanalytics-snowplow-site-search
        :file: ./public/deduplicate/com-snowplowanalytics-snowplow-site-search.sql
      - :name: com-snowplowanalytics-snowplow-timing
        :file: ./public/deduplicate/com-snowplowanalytics-snowplow-timing.sql