:targets:
  - :name:     snowplow-dev  # Insert your own name to identify the database
    :type:     redshift
    :host:     a0007-cxar-ato-clickstream.c9gybgr1jgvx.us-west-2.redshift.amazonaws.com  # Insert Redshfit host
    :database: snowplowprod  # Insert database name
    :port:     5439  # Insert database port
    :username:  # Insert username with relevant credentials to run the below queries
    :password:  # Insert user password
:steps:
  - :name: 01-events
    :queries:
      - :name: events
        :file: ./public/deduplicate/events.sql
  - :name: 02-orders
    :queries:
      - :name: orders
        :file: ./public/deduplicate/orders.sql
  - :name: 03-nordstrom-children
    :queries:
      - :name: nordstrom-add-item
        :file: ./public/deduplicate/nordstrom-add-item.sql
      - :name: nordstrom-elwin-exposures
        :file: ./public/deduplicate/elwin-exposures.sql
      - :name: nordstrom-order-item
        :file: ./public/deduplicate/order-items.sql
      - :name: nordstrom-page-view
        :file: ./public/deduplicate/page-views.sql
      - :name: nordstrom-product-view
        :file: ./public/deduplicate/product-views.sql
      - :name: nordstrom-remove-item
        :file: ./public/deduplicate/nordstrom-remove-item.sql
  - :name: 03-snowplow-children
    :queries:
      - :name: snowplow-add-to-cart
        :file: ./public/deduplicate/snowplow-add-to-cart.sql
      - :name: snowplow-link-click
        :file: ./public/deduplicate/link-clicks.sql
      - :name: snowplow-remove-from-cart
        :file: ./public/deduplicate/snowplow-remove-from-cart.sql
      - :name: snowplow-site-search
        :file: ./public/deduplicate/search.sql
      - :name: snowplow-timing
        :file: ./public/deduplicate/timing.sql