:targets:
  - :name:     snowplow-dev  # Insert your own name to identify the database
    :type:     redshift
    :host:     cxar-ato-clickstream.c9gybgr1jgvx.us-west-2.redshift.amazonaws.com  # Insert Redshfit host
    :database: snowplowdev  # Insert database name
    :port:     5439  # Insert database port
    :username: # Insert username with relevant credentials to run the below queries
    :password: # Insert user password
:steps:
  - :name: 01-sessions
    :queries:
      - :name: 01-localize
        :file: ./localize/01-localize-midnight.sql # An error occured loading the SQL file: /home/ec2-user/playbook/sql/deduplicate/01-events_test.sql