:targets:
  - :name:     snowplow-dev  # Insert your own name to identify the database
    :type:     redshift
    :host:     a0007-cxar-ato-clickstream-jwn.c9gybgr1jgvx.us-west-2.redshift.amazonaws.com  # Insert Redshfit host
    :database: snowplowdev  # Insert database name
    :port:     5439  # Insert database port
    :username:  # Insert username with relevant credentials to run the below queries
    :password:  # Insert user password
:steps:
  - :name: events
    :queries:
      - :name: unload-events
        :file: ./public/unloadToCA/unload-events.sql
  - :name: bag-events
    :queries:
      - :name: unload-nordstrom-add-item
        :file: ./public/unloadToCA/unload-nordstrom-add-item.sql
      - :name: unload-nordstrom-remove-item
        :file: ./public/unloadToCA/unload-nordstrom-remove-item.sql
      - :name: unload-snowplow-add-to-cart
        :file: ./public/unloadToCA/unload-snowplow-add-to-cart.sql
      - :name: unload-snowplow-remove-from-cart
        :file: ./public/unloadToCA/unload-snowplow-remove-from-cart.sql
  - :name: page-and-product-views
    :queries:
      - :name: unload-page-views
        :file: ./public/unloadToCA/unload-page-views.sql
      - :name: unload-product-views
        :file: ./public/unloadToCA/unload-product-views.sql
  - :name: order-items
    :queries:
      - :name: unload-order-items
        :file: ./public/unloadToCA/unload-order-items.sql
  - :name: marketing
    :queries:
      - :name: unload-link-clicks
        :file: ./public/unloadToCA/unload-link-clicks.sql
      - :name: unload-marketing
        :file: ./public/unloadToCA/unload-marketing.sql
      - :name: search
        :file: ./public/unloadToCA/unload-search.sql
      - :name: real-estate
        :file: ./public/unloadToCA/unload-real-estate.sql
      - :name: site-promos
        :file: ./public/unloadToCA/unload-site-promos.sql
  - :name: other
    :queries:
      - :name: unload-timing
        :file: ./public/unloadToCA/unload-timing.sql
      - :name: unload-elwin-exposures
        :file: ./public/unloadToCA/unload-elwin-exposures.sql
      - :name: engagement
        :file: ./public/unloadToCA/unload-engagement.sql