:targets:
  - :name:     snowplow-dev  # Insert your own name to identify the database
    :type:     redshift
    :host:     a0007-cxar-ato-clickstream-jwn.c9gybgr1jgvx.us-west-2.redshift.amazonaws.com  # Insert Redshfit host
    :database: snowplowdev  # Insert database name
    :port:     5439  # Insert database port
    :username: # Insert username with relevant credentials to run the below queries
    :password: # Insert user password
:steps:
  - :name: events
    :queries:
      - :name: events
        :file: ./public/vacuum/events.sql
  - :name: nordstrom-add-item-attrs
    :queries:
      - :name: nordstrom-add-item-attrs
        :file: ./public/vacuum/nordstrom-add-item-attrs.sql
  - :name: nordstrom-elwin-exposures
    :queries:
      - :name: nordstrom-elwin-exposures
        :file: ./public/vacuum/nordstrom-elwin-exposures.sql
  - :name: nordstrom-order-item-attrs
    :queries:
      - :name: nordstrom-order-item-attrs
        :file: ./public/vacuum/nordstrom-order-item-attrs.sql
  - :name: nordstrom-page-view-attrs
    :queries:
      - :name: nordstrom-page-view-attrs
        :file: ./public/vacuum/nordstrom-page-view-attrs.sql
  - :name: nordstrom-product-view-attrs
    :queries:
      - :name: nordstrom-product-view-attrs
        :file: ./public/vacuum/nordstrom-product-view-attrs.sql
  - :name: nordstrom-remove-item-attrs
    :queries:
      - :name: nordstrom-remove-item-attrs
        :file: ./public/vacuum/nordstrom-remove-item-attrs.sql
  - :name: snowplow-add-to-cart
    :queries:
      - :name: snowplow-add-to-cart
        :file: ./public/vacuum/snowplow-add-to-cart.sql
  - :name: snowplow-link-click
    :queries:
      - :name: snowplow-link-click
        :file: ./public/vacuum/snowplow-link-click.sql
  - :name: snowplow-remove-from-cart
    :queries:
      - :name: snowplow-remove-from-cart
        :file: ./public/vacuum/snowplow-remove-from-cart.sql
  - :name: snowplow-site-search
    :queries:
      - :name: snowplow-site-search
        :file: ./public/vacuum/snowplow-site-search.sql
  - :name: snowplow-timing
    :queries:
      - :name: snowplow-timing
        :file: ./public/vacuum/snowplow-timing.sql