:targets:
  - :name:     cust_analytics_dev  # Insert your own name to identify the database
    :type:     redshift
    :host:     a0036-ei-analytics.c9gybgr1jgvx.us-west-2.redshift.amazonaws.com  # Insert Redshfit host
    :database: cust_analytics_dev  # Insert database name
    :port:     5439  # Insert database port
    :username: # Insert username with relevant credentials to run the below queries
    :password: # Insert user password
:steps:
  - :name: 01-02-load-data
    :queries:
      - :name: 01-02-load-data-to-ca
        :file: ./ca/01-02-load-data-to-ca.sql