:targets:
  - :name:     cust_analytics_dev  # Insert your own name to identify the database
    :type:     redshift
    :host:     a0036-ei-analytics.c9gybgr1jgvx.us-west-2.redshift.amazonaws.com  # Insert Redshfit host
    :database: cust_analytics_dev  # Insert database name
    :port:     5439  # Insert database port
    :username:  # Insert username with relevant credentials to run the below queries
    :password:  # Insert user password
:steps:
  - :name: 01-events
    :queries:
      - :name: events
        :file: ./ca/deduplicate/events.sql
  - :name: 02-orders
    :queries:
      - :name: orders
        :file: ./ca/deduplicate/orders.sql
  - :name: 03-nordstrom-children-1
    :queries:
      - :name: nordstrom-add-item
        :file: ./ca/deduplicate/nordstrom-add-item.sql
      - :name: order-items
        :file: ./ca/deduplicate/order-items.sql
      - :name: page-views
        :file: ./ca/deduplicate/page-views.sql
      - :name: product-views
        :file: ./ca/deduplicate/product-views.sql
      - :name: nordstrom-remove-item
        :file: ./ca/deduplicate/nordstrom-remove-item.sql
  - :name: 04-nordstrom-children-2
    :queries:
      - :name: elwin-exposures
        :file: ./ca/deduplicate/elwin-exposures.sql
      - :name: real-estate
        :file: ./ca/deduplicate/real-estate.sql
      - :name: site-promos
        :file: ./ca/deduplicate/site-promos.sql
      - :name: engagement
        :file: ./ca/deduplicate/engagement.sql
  - :name: 05-snowplow-children
    :queries:
      - :name: snowplow-add-to-cart
        :file: ./ca/deduplicate/snowplow-add-to-cart.sql
      - :name: link-clicks
        :file: ./ca/deduplicate/link-clicks.sql
      - :name: snowplow-remove-from-cart
        :file: ./ca/deduplicate/snowplow-remove-from-cart.sql
      - :name: search
        :file: ./ca/deduplicate/search.sql
      - :name: timing
        :file: ./ca/deduplicate/timing.sql